### ISSUE TITLE
BE: Imap bulk actions must filter null messages

### ISSUE THREAD

**Issue by manusa** [manusa/isotope-mail#189]
`final javax.mail.Message[] messages = folder.getMessagesByUID(uids);`

Any null entry in the array should be removed prior to performing any bulk operation in the IMAP folder.

```
java.lang.NullPointerException: null
	at com.sun.mail.imap.Utility.toMessageSet(Utility.java:86)
	at com.sun.mail.imap.Utility.toMessageSetSorted(Utility.java:162)
	at com.sun.mail.imap.IMAPFolder.setFlags(IMAPFolder.java:1439)
	at com.marcnuri.isotope.api.imap.ImapService.setMessagesFlag(ImapService.java:535)
	at com.marcnuri.isotope.api.imap.ImapService.setMessagesSeen(ImapService.java:439)
	at com.marcnuri.isotope.api.imap.ImapService$$FastClassBySpringCGLIB$$9809fc72.invoke(<generated>)
```

**Comment by manusa** [comment]
Application tested, everything working as expected
